### PR TITLE
add README_CN.md

### PR DESCRIPTION
**Pull request by penn201500**
Add README_CN.md 
image

### CODE REVIEW

**Comment by zmh-program** [comment]
some translations are incorrect

**Review by zmh-program — COMMENTED** [review]
Some translations are incorrect

**Comment by penn201500** [comment]
> Some translations are incorrect

Hi, @zmh-program 
I reviewed the doc again. Could you please provide feedback? Specifically, if you notice any translations that seem incorrect or unclear, could you paste those lines into this issue? I'll update them.

**Comment by zmh-program** [comment]
> > Some translations are incorrect
> 
> Hi, @zmh-program 
> I reviewed the doc again. Could you please provide feedback? Specifically, if you notice any translations that seem incorrect or unclear, could you paste those lines into this issue? I'll update them.

firstly thank u very much for your contribution

secondly some of the translations are not my preferred way of translating 
and i want to wait until I have time to fix them myself

(humm guessing your pr was written by AI? 🤔)

**Comment by penn201500** [comment]
> > > Some translations are incorrect
> > 
> > 
> > Hi, @zmh-program
> > I reviewed the doc again. Could you please provide feedback? Specifically, if you notice any translations that seem incorrect or unclear, could you paste those lines into this issue? I'll update them.
> 
> firstly thank u very much for your contribution
> 
> secondly some of the translations are not my preferred way of translating and i want to wait until I have time to fix them myself
> 
> (humm guessing your pr was written by AI? 🤔)

Got it. I translate it with deepl, then fix some awkward expressions manually.

**Comment by zmh-program** [comment]
Hey👋, the content has been updated, any interest in following up on the translation?

**Comment by penn201500** [comment]
working on it

**Comment by penn201500** [comment]
Merge the same pr is better. The Git log is clear.

**Comment by penn201500** [comment]
Already updated the README_CN.md

**Pull request merged**
